name: Bug Report
description: Report a reproducible bug to help improve the organization-template.
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe clearly what you did and what happened instead.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue.
      placeholder: |
        1. Run `tofu plan -lock=false`
        2. Observe the output
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details.
      placeholder: |
        - OS: [e.g., macOS 14.5, Windows 11]
        - OpenTofu version: [e.g., v1.10.5]
        - Azure Provider version: [e.g., 4.45.1]
        - Azure Active Directory Provider version: [e.g., 3.5.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, logs, screenshots, or stack traces about the problem here.
      placeholder: Screenshots, logs, stack traces...
    validations:
      required: false
