name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          CURRENT_TAG=${{ github.ref_name }}
          echo "🚀 New release: $CURRENT_TAG" > release_body.md
          echo "" >> release_body.md

          TAG_COUNT=$(git tag | wc -l)

          if [ "$TAG_COUNT" -le 1 ]; then
            echo "Initial release. All commits included." >> release_body.md
            git log --pretty=format:"- %s (%h)" >> release_body.md
          else
            PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p')
            echo "Changes since $PREV_TAG:" >> release_body.md
            git log --pretty=format:"- %s (%h)" "$PREV_TAG"..HEAD >> release_body.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release_body.md
